# NumPy: Quick Overview

**NumPy** (Numerical Python) is the foundational library for scientific computing in Python. It provides high-performance multidimensional array objects and tools for working with them.

---

### Key Data Structure
* **ndarray:** A fast, memory-efficient $n$-dimensional array providing vectorized operations and broadcasting capabilities.

---

### Key Features
* **Vectorized Operations:** Performs element-wise mathematical calculations without explicit Python `for` loops.
* **Broadcasting:** Allows arithmetic operations on arrays of different shapes automatically.
* **Linear Algebra & Math:** Built-in functions for matrix multiplication, Fourier transforms, random number generation, and statistics.
* **C/C++ Integration:** Serves as the high-performance underlying engine for libraries like Pandas, SciPy, and Scikit-Learn.

---

In [3]:
import numpy as np

In [4]:
import time

In [5]:
size = 100000

In [6]:
list1 = list(range(size))
list2 = list(range(size))

In [7]:
arr1 = np.array(list1)
arr2 = np.array(list2)

In [8]:
start = time.time()
result_list = []
for i in range (size):
    result_list.append(list1[i]+list2[i])
end = time.time()
print("List time: ", end - start)

List time:  0.08231925964355469


In [9]:
start = time.time()
result_array = arr1 +arr2

end = time.time()
print("Numpy time: ", end - start)

Numpy time:  0.0


In [10]:
print(np.__version__)
    

2.5.2


In [11]:
print("hello World")

hello World


In [12]:
list1 = [1,2,3,4,5,6]
array = np.array([1,2,3,4,5,6])
array1 = np.array(list1)
print("list1 : ",list1)
print("array : ",array)
print("array1: ",array1)


list1 :  [1, 2, 3, 4, 5, 6]
array :  [1 2 3 4 5 6]
array1:  [1 2 3 4 5 6]


In [13]:
zeros = np.zeros((2,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
ones = np.ones((2,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


"# for heading in markdown"
Multi dimensional array

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
# 5 dimensional array
arr = np.array([1,2,3,4], ndmin =5)
print(arr)

[[[[[1 2 3 4]]]]]


In [18]:
a = np.array(42)
b = np.array([1,2])
c = np.array([[1,2],[2,4]])
d = np.array([[[2,3,5],[2,4,6],[3,2,1]]])
# d = np.array([[[2,3,5],[2,4],[1]]]) #error
print("a = ",a, " | dimension = ",a.ndim,"\n")
print("b = ",b, " | dimension = ",b.ndim,"\n")
print("c = ",c, " | dimension = ",c.ndim,"\n")
print("d = ",d, " | dimension = ",d.ndim,"\n")


a =  42  | dimension =  0 

b =  [1 2]  | dimension =  1 

c =  [[1 2]
 [2 4]]  | dimension =  2 

d =  [[[2 3 5]
  [2 4 6]
  [3 2 1]]]  | dimension =  3 



In [19]:
d = np.array([[[2,3,5],[2,4,6],[3,2,1]]])
print (d)
d.shape
d.size
print("d.shape: ",d.shape)
print("d.size: ",d.size)

[[[2 3 5]
  [2 4 6]
  [3 2 1]]]
d.shape:  (1, 3, 3)
d.size:  9


Slicing and indexing

In [20]:
array = np.array([1,2,3,4,5,6])
print(array[1])
print(array[1:3])

2
[2 3]


Mathematical operations

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


Aggregation Function (Sum)

In [22]:
arr1 = np.array([1,2,3])
print(np.sum(arr1))

6


Reshape

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr.dtype)
new_arr = arr.reshape(6,1) #if array has not 6 elements then error
print(new_arr)
print(new_arr.shape)
print(new_arr.dtype)

(6,)
int64
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
int64


Random Numbers

In [30]:
np.random.rand(3)

array([0.19583125, 0.1595889 , 0.00173004])

In [31]:
np.random.randint(1,10,5)

array([5, 3, 1, 9, 6], dtype=int32)

In [49]:
arr = np.array([1,2,32,4,5,6],np.int8)
arr
print(arr[2])
lspace = np.linspace(1,10,19)
lspace



32


array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

empty 4 arrays of 6 elements #exponent very small 

In [48]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 1.89146896e-307, 7.56599128e-307,
        2.78145267e-307, 1.29062229e-306, 1.29060531e-306],
       [1.95821439e-306, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.42417221e-306],
       [9.34605037e-307, 6.23059726e-307, 9.34612506e-307,
        6.89804133e-307, 8.45610231e-307, 9.34601642e-307],
       [1.42417221e-306, 1.37961641e-306, 1.42418172e-306,
        1.37961641e-306, 9.45699679e-308, 2.22522596e-306]])

# Empty like
np.empty_like(arr) creates a new array with the same shape and dtype as arr, but filled with uninitialized garbage values (whatever was already in memory) — it does not set them to zero.
Why use it? It's faster than np.zeros_like() or np.ones_like() because it skips initializing the values — useful when you're about to immediately overwrite every element anyway (e.g., in a loop).

In [52]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.empty_like(a)

print(b.shape)   # (2, 3)  -> same shape as a
print(b.dtype)   # int64   -> same dtype as a
print(b)          # random/garbage values, NOT zeros

(2, 3)
int64
[[1 2 3]
 [4 5 6]]


In [53]:
result = np.empty_like(a)
for i in range(a.shape[0]):
    result[i] = a[i] * 2   # filling it right after creation

print(result)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:

emp_like=np.empty_like(lspace)
emp_like

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

Identity Matrix

In [57]:
ide = np.identity(4)

print(ide)
ide.shape

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


(4, 4)

In [58]:
arr = np.arange(99)
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

# combining Arrays

In [60]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Axis 0: Row ( Horizontal Lines - ) 
# Axis 1: Column ( Vertical lines | )
(3,      33)

(rows, columns)

(axis0, Axis1)

In [76]:
arr = np.array([[1,2,3],[4,6,6],[7,1,0]])
print(arr)
print(arr.sum())
print(arr.sum(0))
print(arr.sum(axis=1))

[[1 2 3]
 [4 6 6]
 [7 1 0]]
30
[12  9  9]
[ 6 16  8]


In [ ]:
print(arr.T) #transpose

[[1 4 7]
 [2 6 1]
 [3 6 0]]


In [83]:
arr.flat
for item in arr.flat:
    print(item) 

1
2
3
4
6
6
7
1
0


&emsp;index "&emsp ;" for 4 space

1&emsp;0

2&emsp;1     

3&emsp;2

4&emsp;3

6&emsp;4

6&emsp;5

7&emsp;6

1&emsp;7

0&emsp;8

In [88]:
print (arr.ndim)
print (arr.size)
print (arr.nbytes)

2
9
72


In [ ]:
arr.argmin() # tells index of minimum value

np.int64(8)

In [90]:
arr

array([[1, 2, 3],
       [4, 6, 6],
       [7, 1, 0]])

In [91]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [97]:
arr.argmax(0)

array([2, 1, 1])

In [100]:
ar = np.array([[1, 9, 8],
       [4, 6, 6],
       [7, 1, 0]])
ar

array([[1, 9, 8],
       [4, 6, 6],
       [7, 1, 0]])

In [101]:
ar.argmax(0)

array([2, 0, 0])

In [102]:
ar.max(1)

array([9, 6, 7])

In [103]:
ar.argmax(1)

array([1, 1, 0])

In [112]:
arr1 =np.array([1,3,5,7,9])
tuple(np.where(arr1>5))

(array([3, 4]),)

In [ ]:
arr1 =np.array([[1,3,5,7,9 ],
                [2,4,6,8,10]])
tuple(np.where(arr1>5))

(array([0, 0, 1, 1, 1]), array([3, 4, 2, 3, 4]))

| Row | Col | Value | Condition |
|:---:|:---:|:---:|:---:|
| 0 | 3 | 7 | ✅ True |
| 0 | 4 | 9 | ✅ True |
| 1 | 2 | 6 | ✅ True |
| 1 | 3 | 8 | ✅ True |
| 1 | 4 | 10 | ✅ True |

In [118]:
np.count_nonzero(arr1)

np.int64(10)

In [119]:
np.nonzero(arr1)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))