# NumPy: Quick Overview

**NumPy** (Numerical Python) is the foundational library for scientific computing in Python. It provides high-performance multidimensional array objects and tools for working with them.

---

### Key Data Structure
* **ndarray:** A fast, memory-efficient $n$-dimensional array providing vectorized operations and broadcasting capabilities.

---

### Key Features
* **Vectorized Operations:** Performs element-wise mathematical calculations without explicit Python `for` loops.
* **Broadcasting:** Allows arithmetic operations on arrays of different shapes automatically.
* **Linear Algebra & Math:** Built-in functions for matrix multiplication, Fourier transforms, random number generation, and statistics.
* **C/C++ Integration:** Serves as the high-performance underlying engine for libraries like Pandas, SciPy, and Scikit-Learn.

---

In [2]:
import numpy as np

In [3]:
import time

In [4]:
size = 100000

In [5]:
list1 = list(range(size))
list2 = list(range(size))

In [6]:
arr1 = np.array(list1)
arr2 = np.array(list2)

In [7]:
start = time.time()
result_list = []
for i in range (size):
    result_list.append(list1[i]+list2[i])
end = time.time()
print("List time: ", end - start)

List time:  0.07942724227905273


In [8]:
start = time.time()
result_array = arr1 +arr2

end = time.time()
print("Numpy time: ", end - start)

Numpy time:  0.03457355499267578


In [9]:
print(np.__version__)

2.5.2


In [10]:
print("hello World")

hello World


In [11]:
list1 = [1,2,3,4,5,6]
array = np.array([1,2,3,4,5,6])
array1 = np.array(list1)
print("list1 : ",list1)
print("array : ",array)
print("array1: ",array1)


list1 :  [1, 2, 3, 4, 5, 6]
array :  [1 2 3 4 5 6]
array1:  [1 2 3 4 5 6]


In [12]:
zeros = np.zeros((2,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
ones = np.ones((2,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


"# for heading in markdown"
Multi dimensional array

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
# 5 dimensional array
arr = np.array([1,2,3,4], ndmin =5)
print(arr)

[[[[[1 2 3 4]]]]]


In [17]:
a = np.array(42)
b = np.array([1,2])
c = np.array([[1,2],[2,4]])
d = np.array([[[2,3,5],[2,4,6],[3,2,1]]])
# d = np.array([[[2,3,5],[2,4],[1]]]) #error
print("a = ",a, " | dimension = ",a.ndim,"\n")
print("b = ",b, " | dimension = ",b.ndim,"\n")
print("c = ",c, " | dimension = ",c.ndim,"\n")
print("d = ",d, " | dimension = ",d.ndim,"\n")


a =  42  | dimension =  0 

b =  [1 2]  | dimension =  1 

c =  [[1 2]
 [2 4]]  | dimension =  2 

d =  [[[2 3 5]
  [2 4 6]
  [3 2 1]]]  | dimension =  3 



In [18]:
d = np.array([[[2,3,5],[2,4,6],[3,2,1]]])
print (d)
d.shape
d.size
print("d.shape: ",d.shape)
print("d.size: ",d.size)

[[[2 3 5]
  [2 4 6]
  [3 2 1]]]
d.shape:  (1, 3, 3)
d.size:  9


Slicing and indexing

In [19]:
array = np.array([1,2,3,4,5,6])
print(array[1])
print(array[1:3])

2
[2 3]


Mathematical operations

In [20]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


Aggregation Function (Sum)

In [21]:
arr1 = np.array([1,2,3])
print(np.sum(arr1))

6


Reshape

In [22]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr.dtype)
new_arr = arr.reshape(6,1) #if array has not 6 elements then error
print(new_arr)
print(new_arr.shape)
print(new_arr.dtype)

(6,)
int64
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
int64


Random Numbers

In [23]:
np.random.rand(3)

array([0.70262553, 0.82500336, 0.89686902])

In [24]:
np.random.randint(1,10,5)

array([8, 5, 8, 3, 8], dtype=int32)

In [25]:
arr = np.array([1,2,32,4,5,6],np.int8)
arr
print(arr[2])
lspace = np.linspace(1,10,19)
lspace



32


array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

empty 4 arrays of 6 elements #exponent very small 

In [26]:
emp = np.empty((4,6))
emp

array([[ 1.04914965e-153,  9.08366791e+223,  5.82381891e-144,
         6.17582057e-322,  0.00000000e+000, -1.03227302e-310],
       [ 9.36863747e-312,  3.16202013e-322,  0.00000000e+000,
         0.00000000e+000,  1.70162063e+199,  5.93876745e-038],
       [ 1.22194926e+165,  3.79758808e+175,  9.91835979e+164,
         6.17325549e-062,  1.18806921e-075,  1.57456705e+161],
       [ 2.57294336e-056, -1.10781600e-310,  1.32818767e-075,
         5.42984176e-143,  3.59751658e+252,  1.46901661e+179]])

# Empty like
np.empty_like(arr) creates a new array with the same shape and dtype as arr, but filled with uninitialized garbage values (whatever was already in memory) — it does not set them to zero.
Why use it? It's faster than np.zeros_like() or np.ones_like() because it skips initializing the values — useful when you're about to immediately overwrite every element anyway (e.g., in a loop).

In [27]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.empty_like(a)

print(b.shape)   # (2, 3)  -> same shape as a
print(b.dtype)   # int64   -> same dtype as a
print(b)          # random/garbage values, NOT zeros

(2, 3)
int64
[[     140715186019464 -4611686014132420608                    0]
 [                   0                    0                    0]]


In [28]:
result = np.empty_like(a)
for i in range(a.shape[0]):
    result[i] = a[i] * 2   # filling it right after creation

print(result)

[[ 2  4  6]
 [ 8 10 12]]


In [29]:

emp_like=np.empty_like(lspace)
emp_like

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

Identity Matrix

In [30]:
ide = np.identity(4)

print(ide)
ide.shape

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


(4, 4)

In [31]:
arr = np.arange(99)
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

# combining Arrays

In [32]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Axis 0: Row ( Horizontal Lines - ) 
# Axis 1: Column ( Vertical lines | )
(3,      33)

(rows, columns)

(axis0, Axis1)

In [33]:
arr = np.array([[1,2,3],[4,6,6],[7,1,0]])
print(arr)
print(arr.sum())
print(arr.sum(0))
print(arr.sum(axis=1))

[[1 2 3]
 [4 6 6]
 [7 1 0]]
30
[12  9  9]
[ 6 16  8]


In [34]:
print(arr.T) #transpose

[[1 4 7]
 [2 6 1]
 [3 6 0]]


In [35]:
arr.flat
for item in arr.flat:
    print(item) 

1
2
3
4
6
6
7
1
0


&emsp;index "&emsp ;" for 4 space

1&emsp;0

2&emsp;1     

3&emsp;2

4&emsp;3

6&emsp;4

6&emsp;5

7&emsp;6

1&emsp;7

0&emsp;8

In [36]:
print (arr.ndim)
print (arr.size)
print (arr.nbytes)

2
9
72


In [37]:
arr.argmin() # tells index of minimum value

np.int64(8)

In [38]:
arr

array([[1, 2, 3],
       [4, 6, 6],
       [7, 1, 0]])

In [39]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [40]:
arr.argmax(0)

array([2, 1, 1])

In [41]:
ar = np.array([[1, 9, 8],
       [4, 6, 6],
       [7, 1, 0]])
ar

array([[1, 9, 8],
       [4, 6, 6],
       [7, 1, 0]])

In [42]:
ar.argmax(0)

array([2, 0, 0])

In [43]:
ar.max(1)

array([9, 6, 7])

In [44]:
ar.argmax(1)

array([1, 1, 0])

In [45]:
arr1 =np.array([1,3,5,7,9])
tuple(np.where(arr1>5))

(array([3, 4]),)

In [46]:
arr1 =np.array([[1,3,5,7,9 ],
                [2,4,6,8,10]])
tuple(np.where(arr1>5))

(array([0, 0, 1, 1, 1]), array([3, 4, 2, 3, 4]))

| Row | Col | Value | Condition |
|:---:|:---:|:---:|:---:|
| 0 | 3 | 7 | ✅ True |
| 0 | 4 | 9 | ✅ True |
| 1 | 2 | 6 | ✅ True |
| 1 | 3 | 8 | ✅ True |
| 1 | 4 | 10 | ✅ True |

In [47]:
np.count_nonzero(arr1)

np.int64(10)

In [48]:
np.nonzero(arr1)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [49]:
%whos

Variable       Type       Data/Info
-----------------------------------
a              ndarray    2x3: 6 elems, type `int64`, 48 bytes
ar             ndarray    3x3: 9 elems, type `int64`, 72 bytes
arr            ndarray    3x3: 9 elems, type `int64`, 72 bytes
arr1           ndarray    2x5: 10 elems, type `int64`, 80 bytes
arr2           ndarray    3: 3 elems, type `int64`, 24 bytes
array          ndarray    6: 6 elems, type `int64`, 48 bytes
array1         ndarray    6: 6 elems, type `int64`, 48 bytes
b              ndarray    2x3: 6 elems, type `int64`, 48 bytes
c              ndarray    2x2: 4 elems, type `int64`, 32 bytes
d              ndarray    1x3x3: 9 elems, type `int64`, 72 bytes
emp            ndarray    4x6: 24 elems, type `float64`, 192 bytes
emp_like       ndarray    19: 19 elems, type `float64`, 152 bytes
end            float      1789199402.4591775
i              int        1
ide            ndarray    4x4: 16 elems, type `float64`, 128 bytes
item           int64      0
